services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ai_research_user
      POSTGRES_PASSWORD: ai_research_password
      POSTGRES_DB: ai_research_db
    ports:
      - "55433:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "56380:6379"
  pg_admin:
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: rootpassword
    ports:
      - "18081:80"
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
