version: '3.8'

services:
  db:
    image: postgres:15
    container_name: research_pg
    restart: always
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: tantantan@123
      POSTGRES_DB: ai_research_db
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  pg_admin:
    image: dpage/pgadmin4
    container_name: research_pgadmin
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local