import type { AdminArticleDetail } from './types';

export const adminArticleDetailSeed: Record<string, AdminArticleDetail> = {
  'ART-9921': {
    articleId: 'ART-9921',
    articleTitle: 'Tac dong cua AI trong y te',
    status: 'Completed',
    totalTokens: 12800,
    totalEstimatedCost: 0.082,
    averageLatencySeconds: 4.2,
    modelLabels: ['Gemini Flash', 'Gemini Pro'],
    tokenDeltaPercent: 4,
    costDeltaPercent: 1.2,
    latencyDeltaSeconds: 0.5,
    executionSteps: [
      {
        stepNumber: 1,
        title: 'De xuat bo cuc tong the',
        stageType: 'Structure Recommendation',
        modelName: 'gemini-2.5-flash',
        inputTokens: 1200,
        outputTokens: 800,
        totalTokens: 2000,
        estimatedCost: 0.015,
        latencySeconds: 2.1,
        status: 'completed',
        note: 'He thong sinh cac phuong an chapter flow cho bai tong quan.',
      },
      {
        stepNumber: 2,
        title: 'Chot chuong 1 va cau hinh nguon',
        stageType: 'Chapter Confirm',
        modelName: 'gemini-2.5-flash',
        inputTokens: 1850,
        outputTokens: 950,
        totalTokens: 2800,
        estimatedCost: 0.011,
        latencySeconds: 2.8,
        status: 'cached',
        note: 'Nguoi dung chon title, brief, guide va source cho chuong mo dau.',
      },
      {
        stepNumber: 3,
        title: 'Sinh noi dung cac chuong nghien cuu',
        stageType: 'Chapter Generation',
        modelName: 'gemini-3.1-pro',
        inputTokens: 4500,
        outputTokens: 2100,
        totalTokens: 6600,
        estimatedCost: 0.028,
        latencySeconds: 5.2,
        status: 'generated',
        note: 'Backend goi model de viet tung chuong dua tren blueprint va source da chot.',
      },
      {
        stepNumber: 4,
        title: 'Hop nhat bai va xuat ket qua cuoi',
        stageType: 'Article Finalization',
        modelName: 'gemini-3.1-pro',
        inputTokens: 600,
        outputTokens: 800,
        totalTokens: 1400,
        estimatedCost: 0.028,
        latencySeconds: 6.7,
        status: 'completed',
        note: 'Tong hop section cache, format citation va san sang cho man hinh ket qua.',
      },
    ],
  },
  'ART-9918': {
    articleId: 'ART-9918',
    articleTitle: 'Toi uu hoa logistics bang machine learning',
    status: 'Completed',
    totalTokens: 10440,
    totalEstimatedCost: 0.061,
    averageLatencySeconds: 3.6,
    modelLabels: ['Gemini Flash'],
    tokenDeltaPercent: 2,
    costDeltaPercent: 0.8,
    latencyDeltaSeconds: 0.4,
    executionSteps: [
      {
        stepNumber: 1,
        title: 'De xuat bo cuc tong the',
        stageType: 'Structure Recommendation',
        modelName: 'gemini-2.5-flash',
        inputTokens: 980,
        outputTokens: 620,
        totalTokens: 1600,
        estimatedCost: 0.007,
        latencySeconds: 1.9,
        status: 'completed',
        note: 'Sinh layout chuong nghien cuu cho chu de logistics.',
      },
      {
        stepNumber: 2,
        title: 'Goi y title brief guide source',
        stageType: 'Chapter Recommendation',
        modelName: 'gemini-2.5-flash',
        inputTokens: 2400,
        outputTokens: 1240,
        totalTokens: 3640,
        estimatedCost: 0.016,
        latencySeconds: 3.1,
        status: 'cached',
        note: 'Cac buoc recommendation duoc cache lai de nguoi dung chon.',
      },
      {
        stepNumber: 3,
        title: 'Sinh noi dung chuong',
        stageType: 'Chapter Generation',
        modelName: 'gemini-2.5-flash',
        inputTokens: 2100,
        outputTokens: 1700,
        totalTokens: 3800,
        estimatedCost: 0.022,
        latencySeconds: 4.5,
        status: 'generated',
        note: 'Sinh cac section noi dung dua tren nguon da duoc xac nhan.',
      },
      {
        stepNumber: 4,
        title: 'Hoan tat bai viet',
        stageType: 'Article Finalization',
        modelName: 'gemini-2.5-flash',
        inputTokens: 700,
        outputTokens: 700,
        totalTokens: 1400,
        estimatedCost: 0.016,
        latencySeconds: 4.9,
        status: 'completed',
        note: 'Ghep section, canh lai title va tao payload hien thi cho frontend.',
      },
    ],
  },
};
