"""Add User table And relation with SearchRequest, ResearchArticle

Revision ID: 1ca645ad1493
Revises: ea2561a45fe1
Create Date: 2026-02-21 16:37:13.975865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca645ad1493'
down_revision: Union[str, Sequence[str], None] = 'ea2561a45fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('research_articles', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'research_articles', 'users', ['user_id'], ['id'])
    op.add_column('search_requests', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'search_requests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_requests', type_='foreignkey')
    op.drop_column('search_requests', 'user_id')
    op.drop_constraint(None, 'research_articles', type_='foreignkey')
    op.drop_column('research_articles', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
