"""init tables file

Revision ID: 71804875f7f7
Revises: 
Create Date: 2026-02-17 19:22:42.665594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71804875f7f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_sections', sa.Column('order', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paper_sections', 'research_articles', ['article_id'], ['id'])
    op.drop_column('paper_sections', 'page_number')
    op.drop_column('paper_sections', 'level')
    op.drop_column('paper_sections', 'section_summary')
    op.drop_column('paper_sections', 'paper_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_sections', sa.Column('paper_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('paper_sections', sa.Column('section_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('paper_sections', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('paper_sections', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'paper_sections', type_='foreignkey')
    op.drop_column('paper_sections', 'order')
    # ### end Alembic commands ###
